# Generated by Django 6.0.2 on 2026-03-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableLikesSaves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('liked', models.IntegerField(blank=True, null=True)),
                ('saved', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_likes_saves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablePost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_text', models.CharField(blank=True, max_length=255, null=True)),
                ('time_posted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablePostComments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'table_post_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablePostImg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'table_post_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablePostVid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vid_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'table_post_vid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('passkey', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'table_user',
                'managed': False,
            },
        ),
    ]
